name: assignments
description: A new Flutter project.

version: 1.1.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^6.1.1
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.2
  equatable: ^1.2.5
  faker: ^1.3.0
  flash: ^1.3.1
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  injectable: ^1.0.7
  loading_overlay: ^0.2.1
  numberpicker: ^1.3.0
  sailor: ^0.7.1
  simple_animations: ^2.4.2
  simple_gesture_detector: ^0.1.6
  supercharged: ^1.12.0

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.7
  lint: null

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  localizely:
    project_id: 68ece90c-a18b-4ff9-9013-f1b20cb9a96a
