name: assignments
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.9
  back_button_interceptor: ^4.4.0
  cupertino_icons: ^1.0.2
  faker: ^1.3.0
  flash: ^1.3.1
  flutter_mobx: ^1.1.0+2
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  kiwi: ^2.1.1
  mobx: ^1.2.1+4
  numberpicker: ^1.3.0
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  simple_gesture_detector: ^0.1.6

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: null
  hive_generator: ^0.8.2
  lint: ^1.5.1
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - locales/EN_US.json
    - locales/AR_SA.json
