name: assignments
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  simple_gesture_detector: ^0.1.4
  flash: ^1.2.4
  back_button_interceptor: ^4.2.3
  numberpicker: ^1.2.0
  google_fonts: ^0.5.0+1

  path_provider: ^1.6.5

  kiwi: ^0.2.0
  auto_route: ^0.4.4

  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  shared_preferences: ^0.5.6+3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  cupertino_icons: ^0.1.2
  lint: ^1.1.1

  intl: ^0.16.0
  faker: ^1.2.1

dev_dependencies:
  mobx_codegen: ^1.0.3
  auto_route_generator: ^0.4.4

  hive_generator: any
  build_runner: ^1.8.1

flutter:
  uses-material-design: true

  assets:
    - locales/EN_US.json
    - locales/AR_SA.json
